### ISSUE TITLE
typescript compatibility issue

### ISSUE THREAD

**Issue by yash2code** [gcavancer/cra-redux-saga#1]
When using it with typescript, it is giving error mentioned below:

_**Expected 2 arguments, but got 1.ts(2554)
index.d.ts(60, 3): An argument for 'action' was not provided.
(alias) connectRouter(history: History<any>): Reducer<RouterState, LocationChangeAction>
import connectRouter**_

for this code:

`export default createStore(
  connectRouter(history)(rootReducer),
  initialState,
  composedEnhancers
);`

**Comment by gcavancer** [comment]
Unable to reproduce, as expected, though a future TS version is an option.

**Comment by yash2code** [comment]
> Unable to reproduce, as expected, though a future TS version is an option.

try with latest dependencies . here are mine:

"dependencies": {
    "@blueprintjs/core": "^3.12.0",
    "@types/jest": "23.3.13",
    "@types/moment-timezone": "^0.5.10",
    "@types/node": "10.12.19",
    "@types/react": "16.7.22",
    "@types/react-dom": "16.0.11",
    "@types/react-redux": "^7.0.1",
    "@types/react-router-dom": "^4.3.1",
    "axios": "^0.18.0",
    "connected-react-router": "^6.3.0",
    "node-sass-chokidar": "^1.3.4",
    "react": "^16.7.0",
    "react-dom": "^16.7.0",
    "react-redux": "^6.0.0",
    "react-router-dom": "^4.3.1",
    "react-scripts": "2.1.3",
    "redux": "^4.0.1",
    "redux-saga": "^1.0.1",
    "typescript": "3.2.4"
  },
